# Autogenerated wrapper script for KMC_jll for x86_64-w64-mingw32-cxx03
export kmc, kmc_dump, kmc_tools, libkmc_core

using Zlib_jll
JLLWrappers.@generate_wrapper_header("KMC")
JLLWrappers.@declare_library_product(libkmc_core, "libkmc_core.dll")
JLLWrappers.@declare_executable_product(kmc)
JLLWrappers.@declare_executable_product(kmc_dump)
JLLWrappers.@declare_executable_product(kmc_tools)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libkmc_core,
        "bin\\libkmc_core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        kmc,
        "bin\\kmc.exe",
    )

    JLLWrappers.@init_executable_product(
        kmc_dump,
        "bin\\kmc_dump.exe",
    )

    JLLWrappers.@init_executable_product(
        kmc_tools,
        "bin\\kmc_tools.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
